apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  selector:
    app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: ururaicampos/kubia
          readinessProbe:
            exec:
              command:
                - ls
                - /var/ready